In [14]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix


In [8]:
dataset = pd.read_csv('iris.data')
X = dataset.drop(['Iris-setosa'], axis=1)
y = dataset['Iris-setosa']
scaler = StandardScaler()
X = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

In [12]:
model = LogisticRegression(multi_class='auto', solver='lbfgs')
model.fit(X_train, y_train)


LogisticRegression()

In [15]:
y_pred = model.predict(X_test)
matriz_confusao = confusion_matrix(y_test, y_pred)
print(matriz_confusao)

[[6 0 0]
 [0 4 2]
 [0 0 3]]
