This is a companion notebook for the book [Deep Learning with Python, Second Edition](https://www.manning.com/books/deep-learning-with-python-second-edition?a_aid=keras&a_bid=76564dff). For readability, it only contains runnable code blocks and section titles, and omits everything else in the book: text paragraphs, figures, and pseudocode.

**If you want to be able to follow what's going on, I recommend reading the notebook side by side with your copy of the book.**

This notebook was generated for TensorFlow 2.6.

# The mathematical building blocks of neural networks

## A first look at a neural network

**Loading the MNIST dataset in Keras**

In [1]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


1) Dado o tensor que representa as imagens de treino e teste, apresente para os dados de treino e de teste:

In [8]:
train_images[0,:,:]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

a) O número de amostras.

In [9]:
train_images.shape[0]

60000

b) A quantidade de eixos (ou rank).

In [7]:
train_images.ndim

3

c) O número de dimensões de cada eixo.

In [10]:
train_images.shape

(60000, 28, 28)

d) As labels (ou classes).

In [12]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

**The network architecture**

2) Defina a arquitetura da rede preenchendo o valor do parâmetro referente a função de ativação da última camada, conforme exemplo visto.

In [13]:
from tensorflow import keras
from tensorflow.keras import layers
model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
])

**The compilation step**

3) Compile o modelo preenchendo o valor dos parâmetros referentes ao otimizador e a função de perda, conforme o exemplo visto.

In [20]:
model.compile(optimizer="rmsprop" , loss="sparse_categorical_crossentropy"  , metrics=["accuracy", "top_k_categorical_accuracy"])

**Preparing the image data**

In [15]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

In [16]:
train_images.ndim

2

**"Fitting" the model**

4) Treine o modelo usando os dados de treino, 7 épocas e um tamanho de batch de 256.

In [22]:
model.fit(x=train_images,y=train_labels , epochs=7, batch_size=256, validation_split=0.1)

Epoch 1/7
211/211 [==============================] - 3s 16ms/step - loss: 0.0041 - accuracy: 0.9990 - top_k_categorical_accuracy: 0.2523 - val_loss: 0.0053 - val_accuracy: 0.9987 - val_top_k_categorical_accuracy: 0.2820
Epoch 2/7
211/211 [==============================] - 3s 15ms/step - loss: 0.0032 - accuracy: 0.9994 - top_k_categorical_accuracy: 0.2576 - val_loss: 0.0063 - val_accuracy: 0.9987 - val_top_k_categorical_accuracy: 0.2685
Epoch 3/7
211/211 [==============================] - 3s 15ms/step - loss: 0.0026 - accuracy: 0.9993 - top_k_categorical_accuracy: 0.2568 - val_loss: 0.0055 - val_accuracy: 0.9993 - val_top_k_categorical_accuracy: 0.2298
Epoch 4/7
211/211 [==============================] - 3s 15ms/step - loss: 0.0020 - accuracy: 0.9995 - top_k_categorical_accuracy: 0.2591 - val_loss: 0.0079 - val_accuracy: 0.9987 - val_top_k_categorical_accuracy: 0.2962
Epoch 5/7
211/211 [==============================] - 3s 15ms/step - loss: 0.0017 - accuracy: 0.9996 - top_k_categorical_

**Using the model to make predictions**

5) Selecione 5 amostras de teste e utilize o modelo para prever suas classes. Apresente as classes preditas, os valores reais da classe das amostras escolhidas e a imagem referente à amostra.

In [24]:
predicoes = model.predict(test_images[:5])

In [25]:
import numpy as np

In [28]:
np.argmax(predicoes, axis=1)

array([7, 2, 1, 0, 4])

**Evaluating the model on new data**

6) Avalie o modelo usando os dados de teste. Imprima a curácia obtida.

In [31]:
test_loss, test_acc, test_topk = model.evaluate(test_images,test_labels)

313/313 [==============================] - 1s 3ms/step - loss: 0.0993 - accuracy: 0.9796 - top_k_categorical_accuracy: 0.2337


In [32]:
test_loss, test_acc, test_topk 

(0.09933841228485107, 0.9796000123023987, 0.2337000072002411)

## Data representations for neural networks

O código a seguir traz um exemplo de tensores com diferentes ranks, apenas execute.

### Scalars (rank-0 tensors)

In [ ]:
import numpy as np
x = np.array(12)
x

In [ ]:
x.ndim

### Vectors (rank-1 tensors)

In [ ]:
x = np.array([12, 3, 6, 14, 7])
x

In [ ]:
x.ndim

### Matrices (rank-2 tensors)

In [ ]:
x = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]])
x.ndim

### Rank-3 and higher-rank tensors

In [ ]:
x = np.array([[[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]]])
x.ndim